USE [master]
GO
/****** Object:  Database [DB_ACCESO]    Script Date: 26/09/2022 22:10:12 ******/
CREATE DATABASE [DB_ACCESO]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_ACCESO', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_ACCESO.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_ACCESO_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_ACCESO_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DB_ACCESO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_ACCESO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_ACCESO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_ACCESO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_ACCESO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_ACCESO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_ACCESO] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_ACCESO] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_ACCESO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_ACCESO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_ACCESO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_ACCESO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_ACCESO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_ACCESO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_ACCESO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_ACCESO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_ACCESO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DB_ACCESO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_ACCESO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_ACCESO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_ACCESO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_ACCESO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_ACCESO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_ACCESO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_ACCESO] SET RECOVERY FULL 
GO
ALTER DATABASE [DB_ACCESO] SET  MULTI_USER 
GO
ALTER DATABASE [DB_ACCESO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_ACCESO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_ACCESO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_ACCESO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_ACCESO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_ACCESO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DB_ACCESO', N'ON'
GO
ALTER DATABASE [DB_ACCESO] SET QUERY_STORE = OFF
GO
USE [DB_ACCESO]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 26/09/2022 22:10:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[Correo] [varchar](100) NULL,
	[Clave] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[USUARIO] ON 
GO
INSERT [dbo].[USUARIO] ([IdUsuario], [Correo], [Clave]) VALUES (1, N'david@gmail.com', N'123456789')
GO
INSERT [dbo].[USUARIO] ([IdUsuario], [Correo], [Clave]) VALUES (2, N'123@gmail.com', N'123')
GO
INSERT [dbo].[USUARIO] ([IdUsuario], [Correo], [Clave]) VALUES (3, N'12@gmail.com', N'123')
GO
INSERT [dbo].[USUARIO] ([IdUsuario], [Correo], [Clave]) VALUES (4, N'1234@gmail.com', N'123')
GO
SET IDENTITY_INSERT [dbo].[USUARIO] OFF
GO
/****** Object:  StoredProcedure [dbo].[sp_RegistrarUsuario]    Script Date: 26/09/2022 22:10:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[sp_RegistrarUsuario](
@Correo varchar(100),
@Clave varchar(500),
@Registrado bit output,
@Mensaje varchar(100) output
)
as
begin
	if(not exists(select * from USUARIO where Correo = @Correo))
	begin
		insert into USUARIO(Correo,Clave) values (@Correo,@Clave)
		set @Registrado =1
		set @Mensaje = 'Usuario registrado'
	end
	else
	begin
		set @Registrado = 0
		set @Mensaje = 'El correo ya existe'
	end

end
GO
/****** Object:  StoredProcedure [dbo].[sp_ValidarUsuario]    Script Date: 26/09/2022 22:10:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create proc [dbo].[sp_ValidarUsuario](
@Correo varchar(100),
@Clave varchar(500)
)
as
begin
	if(exists(select * from USUARIO where Correo = @Correo and Clave = @Clave))
		select IdUsuario from USUARIO where Correo = @Correo and Clave = @Clave
	else
		select '0'

end
GO
USE [master]
GO
ALTER DATABASE [DB_ACCESO] SET  READ_WRITE 
GO
